### ISSUE TITLE
If U use the methods do not work, U can do this way

### ISSUE THREAD

**Issue by lyciumlee** [mrexodia/TitanHide#37]
U should use the newest visual stdio, and download the wdk with your system version, and to compile it.win10 1809 can use the release version of this sys file.U just to compile it, and it well work well

**Comment by intelligentpotato** [comment]
Can confirm this. Windows 10 1903 x64, the binary from AppVeyor CI didn't work for me. Used VS2019 with the latest WDK to build it myself, now it works.
![image](https://user-images.githubusercontent.com/9324516/67257529-79156980-f49d-11e9-9d90-1284e3e0c89e.png)

**Comment by AxDSan** [comment]
Can ya'll send the latest compiled binaries? it's a pain to build on my end :(

**Comment by AxDSan** [comment]
> Can confirm this. Windows 10 1903 x64, the binary from AppVeyor CI didn't work for me. Used VS2019 with the latest WDK to build it myself, now it works.
> ![image](https://user-images.githubusercontent.com/9324516/67257529-79156980-f49d-11e9-9d90-1284e3e0c89e.png)

you, send the latest compiled binaries? it's a pain to build on my end :( - not to mention I have done the same thing, I have downloaded them from AppVeyor and the driver starts fine until I get to use the functions, none of them seems to work.

Will really appreciate this!
