### ISSUE TITLE
consider supporting shadow SSDT?

### ISSUE THREAD

**Issue by ironxu** [mrexodia/TitanHide#40]
consider supporting shadow SSDT?

**Comment by Mattiwatti** [comment]
What do you want to accomplish by hooking the shadow SSDT?

ScyllaHide has hooks for user32.dll/win32u.dll functions, which is the user mode equivalent of doing this, and these hooks are rarely if ever needed in my experience. Even if you do need this functionality, it's still possible to use a combination of ScyllaHide and TitanHide, using ScyllaHide only for the window function hooks and basic (PEB/NtGlobalFlag etc.) hiding, and TitanHide for the rest.

If you can give a general use case where it would be useful to have a shadow SSDT hook in place, I'll consider adding it. But I expect there isn't really a use case that would justify adding this.

If you merely want to hook some function in the shadow SSDT in your own fork of TitanHide for whatever reason, see [this snippet](https://gist.github.com/Mattiwatti/c2c5b727e866ae43a27ef6505868590e) I posted on the other shadow SSDT issue, which is a basic SSDT hook that can also (on x64 only) hook the shadow SSDT.
