### ISSUE TITLE
NtTerminateProcess hook failed  SYSTEM_SERVICE_EXCEPTION

### ISSUE THREAD

**Issue by ironxu** [mrexodia/TitanHide#43]
>     hNtTerminateProcess = SSDT::Hook("NtTerminateProcess", (void*)HookNtTerminateProcess);
>     if (hNtTerminateProcess)
>         hook_count++;

> NTSTATUS HookNtTerminateProcess(
>     __in_opt HANDLE ProcessHandle,
>     __in NTSTATUS ExitStatus
> )
> {
>     ULONG uPID;
>     NTSTATUS rtStatus;
>     rtStatus = Undocumented::NtTerminateProcess(ProcessHandle, ExitStatus);
>     return rtStatus;
> }

> typedef NTSTATUS(*NTTERMINATEPROCESS)(
>     __in_opt HANDLE ProcessHandle,
>     __in NTSTATUS ExitStatus
>     );
> static NTTERMINATEPROCESS NtTP = 0;
> NTSTATUS NTAPI Undocumented::NtTerminateProcess(
>     __in_opt HANDLE ProcessHandle,
>     __in NTSTATUS ExitStatus)
> {
>     return NtTP(ProcessHandle, ExitStatus);
> }

**Comment by Mattiwatti** [comment]
This is a basic C bug caused by not initializing `NtTP` (other than the initial `= 0` assignment).
Add to `UndocumentedInit()`:
```C++
if(!NtTP)
{
    NtTP = (NTTERMINATEPROCESS)SSDT::GetFunctionAddress("NtTerminateProcess");
    if(!NtTP)
        return false;
}
```
