### ISSUE TITLE
This driver has been blocked from loading

### ISSUE THREAD

**Issue by raichaa** [mrexodia/TitanHide#58]

**Comment by Mattiwatti** [comment]
"This driver has been blocked from loading" is such a vague error that I would guess it is form the service manager and not from the kernel.

Can you try the following?
1. `sc delete TitanHide`
2. Open `regedit`, go to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services` and manually delete the `TitanHide` key if it exists. (`sc` does not always do this immediately.)
3. `sc create TitanHide binPath= %systemroot%\system32\drivers\TitanHide.sys type= kernel` to recreate the driver service.
4. `sc run TitanHide`

If that _still_ doesn't work, please compile and run the following program and report back what it prints (you'll need `ntdll.h` from [here](https://github.com/x64dbg/ScyllaHide/blob/master/3rdparty/ntdll/ntdll.h)).
```C++
#include "ntdll.h"
#include <stdio.h>

#pragma comment(lib, "ntdll.lib")

int main()
{
    BOOLEAN Discard;
    NTSTATUS Status = RtlAdjustPrivilege(SE_LOAD_DRIVER_PRIVILEGE, TRUE, FALSE, &Discard);
    if (!NT_SUCCESS(Status))
    {
        printf("Could not acquire SE_LOAD_DRIVER_PRIVILEGE\n");
        return Status;
    }

    UNICODE_STRING ServiceName = RTL_CONSTANT_STRING(L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\TitanHide");
    Status = NtLoadDriver(&ServiceName);
    if (!NT_SUCCESS(Status))
    {
        printf("NtLoadDriver failed: 0x%08lX\n", Status);
    }
    else
    {
        printf("Driver loaded successfully.\n");
        NtUnloadDriver(&ServiceName);
    }
    return Status;
}
```

**Comment by fireword** [comment]
oh, it is so sad to listen

**Comment by w0ot-net** [comment]
@Mattiwatti Even though OP never replied I wanted to let you know that the time you took to reply to him helped me get the driver loaded. I don't remember exactly what it was but I was trying to load it incorrectly somehow, following your directions worked :)

**Comment by Mattiwatti** [comment]
Great, glad to hear it helped someone at least :)

**Comment by arthures11** [comment]
I'm having the same issue, nothing helped
