### ISSUE TITLE
"sc start TitanHide " return "Failed 2"

### ISSUE THREAD

**Issue by shenhuiqi** [mrexodia/TitanHide#60]
i use win xp sp3 and run in vmware workstation
![image](https://user-images.githubusercontent.com/3941575/123775948-68b7c200-d901-11eb-8ba6-a6d419d319cb.png)

**Comment by greenozon** [comment]
@shenhuiqi 

1)  you need to either install the service with the full path or add the exe file's path to PATH in system environment variables.
``` SC CREATE "Service-Name" binpath="D:\full-path-to-service\service.exe"
```
or 

2) add D:\full-path-to-service\ to PATH variable and use
 ```SC CREATE "Service-Name" binpath="service.exe"
```
