### ISSUE TITLE
maybe Blue Screen in the VM

### ISSUE THREAD

**Issue by fandy0123456** [mrexodia/TitanHide#66]
When I run TitanHide.sys in a virtual machine, if I place the virtual machine in the background for about a minute, 
and then uninstall TitanHide.sys when I return to the virtual machine, it will cause a blue screen

If I place the virtual machine in the background for a few minutes and then return to the virtual machine, it seems that the virtual machine has been restarted and the previous program has been shut down

If I do not run Titanhide.sys, even if I put the virtual machine in the background for a long time, it will not restart or blue screen

VMWare version:16.0.0 build-16894299
VMWare System version:Windows 10 pro,64-bit(Build 19043.1348) 10.0.0.19043

**Comment by fandy0123456** [comment]
Whether I compile TitanHide.sys or download TitanHide.sys from github, this problem will occur. I think it should not be caused by the signature tool

**Comment by mrexodia** [comment]
Check the readme, you need to disable patchguard youself.

**Comment by fandy0123456** [comment]
If the virtual machine is not placed in the background, the blue screen is not displayed. Can be SSDT HOOK normally

**Comment by fandy0123456** [comment]
and，I have signed the driver successfully and it is running normally. The problem will occur only after being placed in the background of the virtual machine for more than one minute.

**Comment by mrexodia** [comment]
Patchguard triggers at random times, you need to disable it properly to not get BSODs.

**Comment by fandy0123456** [comment]
Thank you, I see
