### ISSUE TITLE
VMProtect 3.6 (Build 1406) Anti-debug ——TitanHide

### ISSUE THREAD

**Issue by SNOW-Loli** [mrexodia/TitanHide#70]
I actually discovered this method back in April via DEMO

But in June China leaked VMP3.6, so I'm posting this method
![31649621329075](https://user-images.githubusercontent.com/65940204/176155137-f16ad070-7acb-4987-8bd1-73288744719d.png)
![21649620708430](https://user-images.githubusercontent.com/65940204/176155163-59f6a4b1-c237-43a0-82ce-a3c9fee22563.png)

**Comment by AndyWatterman** [comment]
I confirm this bug, but in my case packer each time loads a different number in variable. If the program is executed under TH, then the value of the variable is overwritten after the NtQueryInformationProcess.
