### ISSUE TITLE
TitanHideGui does not work

### ISSUE THREAD

**Issue by xSanx** [mrexodia/TitanHide#72]
what am I doing wrong ...
![Снимок экрана 2022-08-22 134631](https://user-images.githubusercontent.com/46198990/185903822-222ee7e7-7da5-4961-80a7-b67828bdd8b7.png)
With plugin for x64dbg (Titanhide.dp2) everything is working

**Comment by mrexodia** [comment]
No idea, try the latest version and rename x32dbg.exe to something else. Also run the “dbh” command and check C:\TitanHide.log

**Comment by defaultbr** [comment]
@xSanx  did you got success in this (I know it's old), but I'm trying to use this in 2025 and I receive the same message "a debugger..." and its gameguard too
