### ISSUE TITLE
FindCaveAddress bug

### ISSUE THREAD

**Issue by Kwansy98** [mrexodia/TitanHide#75]
Not all memory of ntoskrnl.exe readable, maybe use MmIsAddressValid to verify before read. My test win10 vm kernel version is 10.0.19041.1741

```

// bug fix simple way
if (!MmIsAddressValid(Code + i))
{
	j = 0;
	continue;
}

```

![titanhidebug](https://user-images.githubusercontent.com/40238421/188544305-e0ec7a95-b198-4c52-b547-70cd4e67c6a0.jpg)

**Comment by Mattiwatti** [comment]
How is it a bug in TitanHide if another driver copies a function and then calls this function with an invalid address?

**Comment by Kwansy98** [comment]
I didn't read the previous code carefully, range is the section of NtFunction(which is always readable) instead of whole ntoskrnl.exe, my mistake :(
