### ISSUE TITLE
Can't bypass VMProtect(latest version?)

### ISSUE THREAD

**Issue by quangnv13** [mrexodia/TitanHide#85]
I'm currently trying to use TitanHide to hide debugger from VMProtect latest version but it still said "found a debugger...". Does anyone test it work with VMProtect currently?

**Comment by mrexodia** [comment]
No, nobody is testing this project and I am not maintaining or using it in any way.

**Comment by quangnv13** [comment]
> No, nobody is testing this project and I am not maintaining or using it in any way.

Could you please suggest me other plugin can integrate with x64dbg(also created by you) can by pass anti-debug?

I was tried ScyllaHide, TitanHide and HyperHide. It seems TitanHide worked before but unfortunately it no longer have you to maintaince it like x64dbg :(

**Comment by mrexodia** [comment]
You can write your own, or submit a pull request here to update it.
